import 'package:daily_hogwarts/core/data/character_model.dart';

final List<Character> characters = [
  Character(
    id: "4c7e6819-a91a-45b2-a454-f931e4a7cce4",
    name: "Harry Potter",
    alternateNames: ["The Boy Who Lived", "The Chosen One"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "31-07-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "green",
    hairColour: "black",
    wand: Wand(
      wood: "holly",
      core: "phoenix feather",
      length: 11.0,
    ),
    patronus: "stag",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Daniel Radcliffe",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/harry.jpg",
  ),
  Character(
    id: "4c7e6819-a91a-45b2-a454-f931e4a7cce3",
    name: "Hermione Granger",
    alternateNames: ["Hermy", "Know-it-all", "Miss Grant", "Herm-own-ninny"],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "19-09-1979",
    yearOfBirth: 1979,
    wizard: true,
    ancestry: "muggleborn",
    eyeColour: "brown",
    hairColour: "brown",
    wand: Wand(
      wood: "vine",
      core: "dragon heartstring",
      length: 10.75,
    ),
    patronus: "otter",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Emma Watson",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/hermione.jpeg",
  ),
  Character(
    id: "4c7e6819-a91a-45b2-a454-f931e4a7cce5",
    name: "Ron Weasley",
    alternateNames: ["Ronnie", "Won-Won"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "01-03-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wand: Wand(
      wood: "willow",
      core: "unicorn tail hair",
      length: 14.0,
    ),
    patronus: "jack russell terrier",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Rupert Grint",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/ron.jpg",
  ),
  Character(
    id: "b415c867-1cff-455e-b194-748662ac2cca",
    name: "Albus Dumbledore",
    alternateNames: ["Professor Dumbledore"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: null,
    yearOfBirth: 1881,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "blue",
    hairColour: "silver",
    wand: Wand(wood: "", core: "", length: null),
    patronus: "Phoenix",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Richard Harris",
    alternateActors: ["Michael Gambon"],
    alive: false,
    image:
        "https://static.wikia.nocookie.net/characters/images/8/88/Dumbledore.jpg/revision/latest?cb=20240824182238",
  ),
  Character(
    id: "67890",
    name: "Severus Snape",
    alternateNames: ["The Half-Blood Prince", "Snape"],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "09-01-1960",
    yearOfBirth: 1960,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "black",
    hairColour: "black",
    wand: Wand(
      wood: "salamander",
      core: "dragon heartstring",
      length: 12.25,
    ),
    patronus: "Doe",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Alan Rickman",
    alternateActors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/snape.jpg",
  ),
  Character(
    id: "9e28d47b-9877-4b78-a82b-6a4ec9c8f88b",
    name: "Minerva McGonagall",
    alternateNames: ["Professor McGonagall"],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "04-10-1935",
    yearOfBirth: 1935,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "green",
    hairColour: "gray",
    wand: Wand(
      wood: "fir",
      core: "dragon heartstring",
      length: 9.75,
    ),
    patronus: "cat",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Maggie Smith",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/mcgonagall.jpg",
  ),
  Character(
    id: "b7d1b8e2-5486-4d12-b2ed-4b4cde4ed11f",
    name: "Rubeus Hagrid",
    alternateNames: ["Hagrid"],
    species: "half-giant",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "06-12-1928",
    yearOfBirth: 1928,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "black",
    hairColour: "black",
    wand: Wand(
      wood: "oak",
      core: "giant's hair",
      length: 16.0,
    ),
    patronus: "none",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Robbie Coltrane",
    alternateActors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/hagrid.png",
  ),
  Character(
    id: "d8e1d8c9-e5f3-4db0-b687-54d7286b1fdc",
    name: "Sirius Black",
    alternateNames: ["Padfoot", "Sirius"],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "03-11-1960",
    yearOfBirth: 1960,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "gray",
    hairColour: "black",
    wand: Wand(
      wood: "blackthorn",
      core: "dragon heartstring",
      length: 12.0,
    ),
    patronus: "black dog",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Gary Oldman",
    alternateActors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/sirius.JPG",
  ),
  Character(
    id: "3c82fa6e-6f8a-497f-a674-52d8e8a0d63f",
    name: "Remus Lupin",
    alternateNames: ["Moony", "Lupin"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "10-03-1960",
    yearOfBirth: 1960,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "gray",
    hairColour: "brown",
    wand: Wand(
      wood: "dogwood",
      core: "unicorn tail hair",
      length: 10.25,
    ),
    patronus: "wolf",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "David Thewlis",
    alternateActors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/lupin.jpg",
  ),
  Character(
    id: "fe2d1f1d-4e29-4cfc-87c3-96f9bfc55e3f",
    name: "Luna Lovegood",
    alternateNames: ["Loony Lovegood"],
    species: "human",
    gender: "female",
    house: "Ravenclaw",
    dateOfBirth: "13-02-1981",
    yearOfBirth: 1981,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "blonde",
    wand: Wand(
      wood: "yew",
      core: "dragon heartstring",
      length: 9.5,
    ),
    patronus: "hare",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Evanna Lynch",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/luna.jpg",
  ),
  Character(
    id: "ad92f9d6-2c59-4f7f-a3e1-4c86345dc89a",
    name: "Draco Malfoy",
    alternateNames: ["Draco"],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "05-06-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "gray",
    hairColour: "blonde",
    wand: Wand(
      wood: "hawthorn",
      core: "unicorn tail hair",
      length: 10.0,
    ),
    patronus: "none",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Tom Felton",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/draco.jpg",
  ),
  Character(
    id: "cf89305d-5e4a-4f2e-849e-c08b8968b23d",
    name: "Neville Longbottom",
    alternateNames: ["Neville"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "30-07-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "brown",
    wand: Wand(
      wood: "ash",
      core: "unicorn tail hair",
      length: 13.0,
    ),
    patronus: "none",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Matthew Lewis",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/neville.jpg",
  ),
  Character(
    id: "f84d28c4-bd65-4b6b-81eb-d2c6651ac5c2",
    name: "Ginny Weasley",
    alternateNames: ["Ginny"],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "11-08-1981",
    yearOfBirth: 1981,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "red",
    wand: Wand(
      wood: "holly",
      core: "phoenix feather",
      length: 9.75,
    ),
    patronus: "horse",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Bonnie Wright",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/ginny.jpg",
  ),
  Character(
    id: "dd925874-e800-4eb4-9f0d-4d0fed15634b",
    name: "Arthur Weasley",
    alternateNames: [],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "06-02-1950",
    yearOfBirth: 1950,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wand: Wand(
      wood: "",
      core: "",
      length: null,
    ),
    patronus: "weasel",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Mark Williams",
    alternateActors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/arthur.jpg",
  ),
  Character(
    id: "6afb1960-febd-418d-b604-e50c1b59459b",
    name: "Bellatrix Lestrange",
    alternateNames: ["Bella"],
    species: "human",
    gender: "female",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: 1951,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "black",
    wand: Wand(
      wood: "walnut",
      core: "dragon heartstring",
      length: 12.75,
    ),
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Helena Bonham Carter",
    alternateActors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/bellatrix.jpg",
  ),
  Character(
    id: "efa802c8-ae18-4ae1-a524-49df21d05939",
    name: "Lord Voldemort",
    alternateNames: [
      "Tom Riddle",
      "Tom Marvolo Riddle",
      "You-Know-Who",
      "He Who Must Not Be Named",
      "the Dark Lord",
      "the Heir of Slytherin",
    ],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "31-12-1926",
    yearOfBirth: 1926,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "Scarlet",
    hairColour: "bald",
    wand: Wand(
      wood: "yew",
      core: "phoenix tail feather",
      length: 13.5,
    ),
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Ralph Fiennes",
    alternateActors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/voldemort.jpg",
  ),
];

final List<Character> teachers =
    characters.where((character) => character.hogwartsStaff).toList();

final List<Character> students =
    characters.where((character) => character.hogwartsStudent).toList();
